server:
  port: 8001

spring:
  application:
    name: cloud-service-provider

#eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka1.forever.com:7001/eureka