server:
  port: 8010

spring:
  application:
    name: cloud-service-consumer

#eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka2.forever.com:7002/eureka